version: "3"

services:
  chopchoprss:
    build: .
    ports:
      - "8090:8090"
    volumes:
      - chopchoprss-data:/data
    restart: unless-stopped
    # Pass a command like "list-feeds" to override the default "serve" command
    # command: list-feeds

volumes:
  chopchoprss-data:
    # This creates a named volume for persistent data
